### ISSUE TITLE
Trigger client build and commit latest changes

### ISSUE THREAD

**Issue by bertearazvan** [DHI-GRAS/terracotta#196]
As the app is built using React and Typescript, the build and the commit of the latest changes added in React should happen in the CI environment before publishing the package. 

As per our discussion @j08lue, the current Travis CI could be moved to GitHub Actions and we can pass to it the `needs` key which would make it wait for the react build commit to happen.

An example of the commit job is 
```
build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/heads/master
      - uses: actions/setup-node@v1
        with:
          node-version: 12

# should cd to the right folder (client/app)

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.4.1
        with:
          commit_message: Commit latest build
          branch: master # should be current branch
```
